# PlayTimeManager - GUIs Configuration
# This file contains all customizable text elements for GUIs (will be added more in the future)
# Hex colors are supported with the following format: &#rrggbb
# where rr (red), gg (green) and bb (blue) are
# hexadecimal values between 00 and ff (same as decimal 0-255)
# Standard minecraft colors and styles are accepted using & format (e.g. "&5&lTest").
#
# Placeholders enclosed in {} are FIELD-DEPENDENT. They can only be used within the specific field
# where they're defined. All available placeholders are shown in this configuration file.

#=================================================================
#                   JOIN STREAKS REWARDS GUI
#=================================================================

rewards-gui:
  gui:
    title: "Claim Your Rewards"
    border-item-name: "&f[&6P.T.M.&f]&7"

  pagination:
    page-indicator: "&e&lPage %CURRENT_PAGE% of %TOTAL_PAGES%"
    next-page:
      name: "&a&lNext Page →"
      lore: "&7Click to view the next page"
    prev-page:
      name: "&a&l← Previous Page"
      lore: "&7Click to view the previous page"
    no-more-pages: "&c&lNo More Pages"
    first-page: "&c&lFirst Page"

  filters:
    claimed:
      enabled-name: "&9&l[ CLAIMED REWARDS ]"
      disabled-name: "&7Claimed Rewards"
      lore-enabled: "&7Currently viewing: &9&lClaimed rewards"
      lore-disabled: "&7Click to view all claimed rewards"
    available:
      enabled-name: "&6&l[ AVAILABLE REWARDS ]"
      disabled-name: "&7Available Rewards"
      lore-enabled: "&7Currently viewing: &6&lAvailable rewards"
      lore-disabled: "&7Click to view rewards ready to claim"
    locked:
      enabled-name: "&4&l[ LOCKED REWARDS ]"
      disabled-name: "&7Locked Rewards"
      lore-enabled: "&7Currently viewing: &4&lLocked rewards"
      lore-disabled: "&7Click to view upcoming rewards"

  claim-all:
    name: "&e&lClaim all"

  no-rewards:
    name: "&l&cNo rewards to display!"
    lore: "&7Try changing your filters"

  reward-items:
    available:
      prefix: "&a&l[CLAIMABLE] "
      lore:
        - "&aThis reward is available to claim!"
        - "&7Click to receive your reward"
    claimed:
      prefix: "&8&l[CLAIMED] "
      lore:
        - "&8You've already claimed this reward"
    locked:
      prefix: "&c&l[LOCKED] "
      lore:
        - "&cYou haven't reached this join streak yet"

    info-lore:
      required-joins: "&7Required Joins: &e%REQUIRED_JOINS%"
      join-streak: "&7Your current join streak: %JOIN_STREAK_COLOR%%CURRENT_STREAK%"
      join-streak-color:
        sufficient: "&a"
        insufficient: "&c"
      description-separator: ""
      description: "&7%DESCRIPTION%"
      reward-description-separator: ""
      reward-description: "&7%REWARD_DESCRIPTION%"

  messages:
    no-permission: "&cYou don't have permission to claim rewards!"
    not-available: "&cThis reward is not available to claim!"
    reward-not-found: "&cCouldn't find the reward details!"
    error-processing: "&cAn error occurred while processing your reward."
    claimed-rewards: "&aClaimed %COUNT% rewards!"

#=================================================================
#                      PLAYER STATS GUI
#=================================================================

player-stats-gui:
  gui:
    title: "&6&l%PLAYER_NAME%'s stats"
    border:
      material: "BLACK_STAINED_GLASS_PANE"
      name: " "

  # Configurable GUI items
  items:
    playtime:
      enabled: true
      slot: 20
      material: "CLOCK"
      name: "&e&lPlaytime Information"
      permission: "playtime.stats.view.playtime"
      lore:
        - "&7Total Playtime: &e%PLAYTIME%"
        - "&7Actual Playtime: &e%ACTUAL_PLAYTIME%"
        - "&7Artificial Playtime: &e%ARTIFICIAL_PLAYTIME%"

    firstjoin:
      enabled: true
      slot: 22
      material: "CAKE"
      name: "&a&lFirst Join"
      permission: "playtime.stats.view.firstjoin"
      lore:
        - "&7First Join: &e%FIRST_JOIN_DATE%"
        - "&7Account Age: &e%ACCOUNT_AGE%"

    lastseen:
      enabled: true
      slot: 24
      material: "COMPASS"
      name: "&c&lLast Seen"
      permission: "playtime.stats.view.lastseen"
      lore:
        - "&7Last Seen: &e%LAST_SEEN_DATE%"
        - "&7Time Elapsed: &e%TIME_SINCE_LAST_SEEN%"

    joinstreak:
      enabled: true
      slot: 30
      material: "FIRE_CHARGE"
      name: "&6&lJoin Streak"
      permission: "playtime.stats.view.joinstreak"
      lore:
        - "&7Current Streak: &e%RELATIVE_STREAK%"
        - "&7Total Streak: &e%ABSOLUTE_STREAK%"

    goals:
      enabled: true
      slot: 32
      material: "NETHER_STAR"
      name: "&d&lCompleted Goals"
      permission: "playtime.stats.view.goals"
      lore:
        - "&7Total Goals: &e%GOALS_COUNT%"
        - "&8&m------------------"
        - "%GOALS_LIST%"

    account:
      enabled: true
      slot: 4
      material: "PLAYER_HEAD"
      name: "&b&lAccount Overview"
      permission: "playtime.stats.view.account"
      lore:
        - "&7Player: &e%PLAYER_NAME%"
        - "&7UUID: &f%UUID%"

    # Refresh button - now treated as a regular configurable item
    refresh:
      enabled: true
      slot: 49
      material: "LIME_DYE"
      name: "&a&lRefresh Stats"
      permission: "playtime.stats.refresh"
      delay: 3
      sound: "UI_BUTTON_CLICK"
      sound-volume: 1.0
      sound-pitch: 1.0
      lore:
        - "&7Click to refresh player statistics"
        - "&8Cooldown: &c%DELAY% seconds"

    # Example of a custom item
    custom_stat:
      enabled: false
      slot: 35
      material: "DIAMOND"
      name: "&b&lCustom Stat"
      permission: "playtime.stats.view.custom"
      lore:
        - "&7This is a custom stat item"
        - "&7Player: &e%PLAYER_NAME%"
        - "&7Add your own placeholders here"

  # Goal display settings
  goals:
    max-display: 5
    list-format: "&7- &e%GOAL%"
    more-format: "&7... and &e%REMAINING% &7more"

  # Messages
  messages:
    player-not-found: "&cPlayer data could not be found!"
    no-permission: "&cYou don't have permission to view this information."
