# ██████╗ ██╗      █████╗ ██╗   ██╗████████╗██╗███╗   ███╗███████╗
# ██╔══██╗██║     ██╔══██╗╚██╗ ██╔╝╚══██╔══╝██║████╗ ████║██╔════╝
# ██████╔╝██║     ███████║ ╚████╔╝    ██║   ██║██╔████╔██║█████╗
# ██╔═══╝ ██║     ██╔══██║  ╚██╔╝     ██║   ██║██║╚██╔╝██║██╔══╝
# ██║     ███████╗██║  ██║   ██║      ██║   ██║██║ ╚═╝ ██║███████╗
# ╚═╝     ╚══════╝╚═╝  ╚═╝   ╚═╝      ╚═╝   ╚═╝╚═╝     ╚═╝╚══════╝
# ███╗   ███╗ █████╗ ███╗   ██╗ █████╗  ██████╗ ███████╗██████╗
# ████╗ ████║██╔══██╗████╗  ██║██╔══██╗██╔════╝ ██╔════╝██╔══██╗
# ██╔████╔██║███████║██╔██╗ ██║███████║██║  ███╗█████╗  ██████╔╝
# ██║╚██╔╝██║██╔══██║██║╚██╗██║██╔══██║██║   ██║██╔══╝  ██╔══██╗
# ██║ ╚═╝ ██║██║  ██║██║ ╚████║██║  ██║╚██████╔╝███████╗██║  ██║
# ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝

#If you are looking for goals settings, please head to the "Goals" folder.
#To make such folder appear you need to create at least one goal -> /playtimegoal set <goalname> time:<time>

#Leave this untouched
config-version: 3.3

#Leave this untouched
goals-config-version: 1.0

#This messaged is showed each time /playtime is executed.
#Available placeholders: %PLAYTIME%, %PLAYER_NAME%
playtime-self-message: "[§6PlayTime§eManager§f]§7 Your playtime is §6%PLAYTIME%"

#This messaged is showed each time /playtime <username> is executed.
#Available placeholders: %PLAYTIME%, %PLAYER_NAME%
playtime-others-message: "[§6PlayTime§eManager§f]§7 The playtime of §e%PLAYER_NAME%§7 is §6%PLAYTIME%"

#goal-check-rate sets every how many seconds a check will be made on online players to see if they have
#reached a new time goal. With many players and a low rate it may cause lag.
#Time should be specified as seconds, default is 15 minutes (900s)
goal-check-rate: 900

#Enable or disable debug logging in the console
#Default: true
goal-check-verbose: true

#Choose your permissions management plugin
#Available options: "luckperms"
#Using a different permissions plugin? Let me know on my GitHub issues page!
permissions-manager-plugin: "luckperms"

# Define the format for displaying dates and times
# Want a different format? You can create your own here: http://www.sdfonlinetester.info/
datetime-format: "MMM dd, yyyy HH:mm:ss"


