# ██████╗ ██╗      █████╗ ██╗   ██╗████████╗██╗███╗   ███╗███████╗
# ██╔══██╗██║     ██╔══██╗╚██╗ ██╔╝╚══██╔══╝██║████╗ ████║██╔════╝
# ██████╔╝██║     ███████║ ╚████╔╝    ██║   ██║██╔████╔██║█████╗
# ██╔═══╝ ██║     ██╔══██║  ╚██╔╝     ██║   ██║██║╚██╔╝██║██╔══╝
# ██║     ███████╗██║  ██║   ██║      ██║   ██║██║ ╚═╝ ██║███████╗
# ╚═╝     ╚══════╝╚═╝  ╚═╝   ╚═╝      ╚═╝   ╚═╝╚═╝     ╚═╝╚══════╝
# ███╗   ███╗ █████╗ ███╗   ██╗ █████╗  ██████╗ ███████╗██████╗
# ████╗ ████║██╔══██╗████╗  ██║██╔══██╗██╔════╝ ██╔════╝██╔══██╗
# ██╔████╔██║███████║██╔██╗ ██║███████║██║  ███╗█████╗  ██████╔╝
# ██║╚██╔╝██║██╔══██║██║╚██╗██║██╔══██║██║   ██║██╔══╝  ██╔══██╗
# ██║ ╚═╝ ██║██║  ██║██║ ╚████║██║  ██║╚██████╔╝███████╗██║  ██║
# ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝

#If you are looking for goals settings, please head to the "Goals" folder.
#To make such folder appear you need to create at least one goal -> /playtimegoal

#leave this untouched
config-version: 3.2

#This messaged is showed each time /playtime is executed.
#Available placeholders: %PLAYTIME%, %PLAYER_NAME%
playtime-self-message: "[§6PlayTime§eManager§f]§7 Your playtime is §6%PLAYTIME%"

#This messaged is showed each time /playtime <username> is executed.
#Available placeholders: %PLAYTIME%, %PLAYER_NAME%
playtime-others-message: "[§6PlayTime§eManager§f]§7 The playtime of §e%PLAYER_NAME%§7 is §6%PLAYTIME%"

#goal-check-rate sets every how many seconds a check will be made on online players to see if they have
#reached a new time goal. With many players and a low rate it may cause lag.
#Time should be specified as seconds, default is 15 minutes (900s)
goal-check-rate: 900

#Set this to false to remove debug messages on console
goal-check-verbose: true

#Specify which permissions plugin to use when assigning permissions and groups to a player
#Available options: "luckperms"
#You can suggest support for more permissions manager plugin if missing!
permissions-manager-plugin: "luckperms"


