name: PlayTimeManager
version: '${project.version}'
main: me.thegabro.playtimemanager.PlayTimeManager
api-version: '1.19'
author: TheGabro
description: A playtime tracker with customization options and automated rewards for efficient monitoring
softdepend: [PlaceholderAPI, LuckPerms]

commands:
  playtime:
    description: Command to get/modify play time stats of players
    permission: playtime
    permission-message: You don't have the permission to execute this command!
  playtimeaverage:
    description: Command to get the average of play time data
    permission: playtime.average
    permission-message: You don't have the permission to execute this command!
    aliases: [ptavg]
  playtimepercentage:
    description: Command to get the % of players that have a playtime greater than or equal to a given one
    permission: playtime.playtimepercentage
    permission-message: You don't have the permission to execute this command!
    aliases: [ptpercent]
  playtimetop:
    description: Command to get the top N players with highest playtime
    permission: playtime.top
    permission-message: You don't have the permission to execute this command!
    aliases: [pttop]
  playtimegoal:
    description: Command to manage goals
    permission: playtime.goal
    permission-message: You don't have the permission to execute this command!
    aliases: [ptgoal]
  playtimereload:
    description: Command to reload the main config
    permission: playtime.reload
    permission-message: You don't have the permission to execute this command!
    aliases: [ptreload]
  playtimebackup:
    description: Command to create a backup of the play_time.db file
    permission: playtime.backup
    permission-message: You don't have the permission to execute this command!
    aliases: [ptbkp]
  playtimejoinstreak:
    description: Command to manage join streak rewards
    permission: playtime.joinstreak
    permission-message: You don't have the permission to execute this command!
    aliases: [ptjsk]
  playtimeattribute:
    description: Command to manage internal players attributes
    permission: playtime.others.attributes
    permission-message: You don't have the permission to execute this command!
    aliases: [ptattr]
  claimrewards:
    description: Command to claim join streak rewards
    permission: playtime.joinstreak.claim
    permission-message: You don't have the permission to execute this command!
permissions:
  playtime.*:
    default: op
    description: Gives access to every command
    children:
      playtime: true
      playtime.others: true
      playtime.others.modify: true
      playtime.others.attributes: true
      playtime.others.modify.all: true
      playtime.others.stats: true
      playtime.average: true
      playtime.percentage: true
      playtime.top: true
      playtime.goal: true
      playtime.reload: true
      playtime.backup: true
      playtime.joinstreak: true
      playtime.joinstreak.claim: true
      playtime.joinstreak.claim.automatic: true
      playtime.joinstreak.seeplayer: true
  playtime:
    default: true
  playtime.others:
    default: false
  playtime.others.modify:
    default: false
  playtime.others.modify.all:
    default: false
  playtime.others.attributes:
    default: false
  playtime.others.stats:
    default: false
  playtime.average:
    default: false
  playtime.percentage:
    default: false
  playtime.top:
    default: false
  playtime.goal:
    default: false
  playtime.reload:
    default: false
  playtime.backup:
    default: false
  playtime.joinstreak:
    default: false
  playtime.joinstreak.claim:
    default: true
  playtime.joinstreak.claim.automatic:
    default: false
  playtime.joinstreak.seeplayer:
    default: false