name: PlayTimeManager
version: '${project.version}'
main: me.thegabro.playtimemanager.PlayTimeManager
api-version: '1.19'
author: TheGabro
description: A playtime tracker with customization options and automated rewards for efficient monitoring
softdepend: [PlaceholderAPI, LuckPerms]

permissions:
  playtime.*:
    default: op
    description: Gives access to every command
    children:
      playtime: true
      playtime.others: true
      playtime.others.modify: true
      playtime.others.modify.all: true
      playtime.others.stats: true
      playtime.average: true
      playtime.percentage: true
      playtime.top: true
      playtime.goal: true
      playtime.reload: true
      playtime.backup: true
      playtime.joinstreak: true
      playtime.joinstreak.claim: true
      playtime.joinstreak.claim.automatic: true
      playtime.joinstreak.seeplayer: true
  playtime:
    default: true
  playtime.others:
    default: false
  playtime.others.modify:
    default: false
  playtime.others.modify.all:
    default: false
  playtime.others.stats:
    default: false
  playtime.average:
    default: false
  playtime.percentage:
    default: false
  playtime.top:
    default: false
  playtime.goal:
    default: false
  playtime.reload:
    default: false
  playtime.backup:
    default: false
  playtime.joinstreak:
    default: false
  playtime.joinstreak.claim:
    default: true
  playtime.joinstreak.claim.automatic:
    default: false
  playtime.joinstreak.seeplayer:
    default: false