name: PlayTimeManager
version: '${project.version}'
main: me.thegabro.playtimemanager.PlayTimeManager
api-version: '1.19'
author: TheGabro
Description: A simple playtime plugin manager

softdepend: [PlaceholderAPI, LuckPerms]

commands:
  playtime:
    description: Command to get/modify play time stats of players
    permission: playtime
    permission-message: You don't have the permission to execute this command!
  playtimeaverage:
    description: Command to get the average of play time data
    permission: playtime.average
    permission-message: You don't have the permission to execute this command!
  playtimepercentage:
    description: Command to get the % of players that have a playtime greater than or equal to a given one
    permission: playtime.playtimepercentage
    permission-message: You don't have the permission to execute this command!
  playtimetop:
    description: Command to get the top N players with highest playtime
    permission: playtime.top
    permission-message: You don't have the permission to execute this command!
  playtimegoal:
    description: Command to manage goals
    permission: playtime.goal
    permission-message: You don't have the permission to execute this command!
  playtimereload:
    description: Command to reload the main config
    permission: playtime.reload
    permission-message: You don't have the permission to execute this command!

permissions:
  playtime.*:
    default: op
    description: Gives access to every command
    children:
      playtime: true
      playtime.others: true
      playtime.others.modify: true
      playtime.others.stats: true
      playtime.average: true
      playtime.percentage: true
      playtime.top: true
      playtime.goal: true
      playtime.reload: true
  playtime:
    default: true
  playtime.others:
    default: false
  playtime.others.modify:
    default: false
  playtime.others.stats:
    default: false
  playtime.average:
    default: false
  playtime.percentage:
    default: false
  playtime.top:
    default: false
  playtime.goal:
    default: false
  playtime.reload:
    default: false