# PlayTimeManager - Rewards GUI Configuration
# This file contains all customizable text elements for the join streak rewards GUI

# Hex colors are supported with the following format: &#rrggbb
# where rr (red), gg (green) and bb (blue) are
# hexadecimal values between 00 and ff (same as decimal 0-255)
# Standard minecraft colors and styles are accepted using & format (e.g. "&5&lTest").

gui:
  title: "&6Claim Your Rewards"
  border-item-name: "&f[&6P.T.M.&f]&7"

pagination:
  page-indicator: "&e&lPage {current_page} of {total_pages}"
  next-page:
    name: "&a&lNext Page →"
    lore: "&7Click to view the next page"
  prev-page:
    name: "&a&l← Previous Page"
    lore: "&7Click to view the previous page"
  no-more-pages: "&c&lNo More Pages"
  first-page: "&c&lFirst Page"

filters:
  claimed:
    enabled-name: "&8&l[CLAIMED] &7Rewards: &a&lON"
    disabled-name: "&8&l[CLAIMED] &7Rewards: &c&lOFF"
    lore-enabled: "&7Click to hide claimed rewards"
    lore-disabled: "&7Click to show claimed rewards"
  available:
    enabled-name: "&a&l[AVAILABLE] &7Rewards: &a&lON"
    disabled-name: "&a&l[AVAILABLE] &7Rewards: &c&lOFF"
    lore-enabled: "&7Click to hide available rewards"
    lore-disabled: "&7Click to show available rewards"
  locked:
    enabled-name: "&c&l[LOCKED] &7Rewards: &a&lON"
    disabled-name: "&c&l[LOCKED] &7Rewards: &c&lOFF"
    lore-enabled: "&7Click to hide locked rewards"
    lore-disabled: "&7Click to show locked rewards"

claim-all:
  name: "&e&lClaim all"

no-rewards:
  name: "&l&cNo rewards to display!"
  lore: "&7Try changing your filters"

reward-items:
  available:
    prefix: "&a&l[CLICK TO CLAIM] "
    lore:
      - "&aThis reward is available to claim!"
      - "&7Click to receive your reward"
  claimed:
    prefix: "&8&l[CLAIMED] "
    lore:
      - "&8You've already claimed this reward"
  locked:
    prefix: "&c&l[LOCKED] "
    lore:
      - "&cYou haven't reached this join streak yet"

  info-lore:
    required-joins: "&7Required Joins: &e{required_joins}"
    join-streak: "&7Your current join streak: {color}{current_streak}"
    join-streak-color:
      sufficient: "&a"
      insufficient: "&c"
    description-separator: ""
    description: "&7{description}"
    reward-description-separator: ""
    reward-description: "&7Reward: {reward_description}"
    permissions-header-separator: ""
    permissions-header: "&7&lPermissions:"
    permission-format: "&7- &f{permission}"
    commands-header-separator: ""
    commands-header: "&7&lCommands:"
    command-format: "&7- &f{command}"

messages:
  no-permission: "&cYou don't have permission to claim rewards!"
  not-available: "&cThis reward is not available to claim!"
  reward-not-found: "&cCouldn't find the reward details!"
  error-processing: "&cAn error occurred while processing your reward."
  claimed-rewards: "&aClaimed {count} rewards!"